--시험지
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (1, 1, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (2, 2, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (3, 3, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (4, 4, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (5, 5, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (6, 6, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (7, 7, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (8, 8, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (9, 9, 1, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (10, 10, 1, '필기');
--오라클
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (11, 11, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (12, 12, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (13, 13, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (14, 14, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (15, 15, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (16, 16, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (17, 17, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (18, 18, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (19, 19, 2, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (20, 20, 2, '필기');
--웹
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (21, 21, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (22, 22, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (23, 23, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (24, 24, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (25, 25, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (26, 26, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (27, 27, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (28, 28, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (29, 29, 3, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (30, 30, 3, '필기');
--JSP
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (31, 31, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (32, 32, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (33, 33, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (34, 34, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (35, 35, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (36, 36, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (37, 37, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (38, 38, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (39, 39, 4, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (40, 40, 4, '필기');
--Spring
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (41, 41, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (42, 42, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (43, 43, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (44, 44, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (45, 45, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (46, 46, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (47, 47, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (48, 48, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (49, 49, 5, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (50, 50, 5, '필기');
--Python
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (51, 51, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (52, 52, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (53, 53, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (54, 54, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (55, 55, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (56, 56, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (57, 57, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (58, 58, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (59, 59, 6, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (60, 60, 6, '필기');
--Django
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (61, 61, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (62, 62, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (63, 63, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (64, 64, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (65, 65, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (66, 66, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (67, 67, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (68, 68, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (69, 69, 7, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (70, 70, 7, '필기');
--Flask
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (71, 71, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (72, 72, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (73, 73, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (74, 74, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (75, 75, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (76, 76, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (77, 77, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (78, 78, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (79, 79, 8, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (80, 80, 8, '필기');
--Swift
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (81, 81, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (82, 82, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (83, 83, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (84, 84, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (85, 85, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (86, 86, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (87, 87, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (88, 88, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (89, 89, 9, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (90, 90, 9, '필기');
--Kotlin
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (91, 91, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (92, 92, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (93, 93, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (94, 94, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (95, 95, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (96, 96, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (97, 97, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (98, 98, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (99, 99, 10, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (100, 100, 10, '필기');
--React
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (101, 101, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (102, 102, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (103, 103, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (104, 104, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (105, 105, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (106, 106, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (107, 107, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (108, 108, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (109, 109, 11, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (110, 110, 11, '필기');
--ElasticSearch
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (111, 111, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (112, 112, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (113, 113, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (114, 114, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (115, 115, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (116, 116, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (117, 117, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (118, 118, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (119, 119, 12, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (120, 120, 12, '필기');
--데이터 구조 알고리즘
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (121, 121, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (122, 122, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (123, 123, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (124, 124, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (125, 125, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (126, 126, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (127, 127, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (128, 128, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (129, 129, 13, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (130, 130, 13, '필기');
--컴퓨터 이론
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (131, 131, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (132, 132, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (133, 133, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (134, 134, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (135, 135, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (136, 136, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (137, 137, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (138, 138, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (139, 139, 14, '필기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (140, 140, 14, '필기');
--JAVA 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (141, 141, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (142, 142, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (143, 143, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (144, 144, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (145, 145, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (146, 146, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (147, 147, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (148, 148, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (149, 149, 1, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (150, 150, 1, '실기');
--오라클 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (151, 151, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (152, 152, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (153, 153, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (154, 154, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (155, 155, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (156, 156, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (157, 157, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (158, 158, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (159, 159, 2, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (160, 160, 2, '실기');
--웹 프론트엔드 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (161, 161, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (162, 162, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (163, 163, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (164, 164, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (165, 165, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (166, 166, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (167, 167, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (168, 168, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (169, 169, 3, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (170, 170, 3, '실기');
--JSP 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (171, 171, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (172, 172, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (173, 173, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (174, 174, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (175, 175, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (176, 176, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (177, 177, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (178, 178, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (179, 179, 4, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (180, 180, 4, '실기');
--Spring 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (181, 181, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (182, 182, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (183, 183, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (184, 184, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (185, 185, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (186, 186, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (187, 187, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (188, 188, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (189, 189, 5, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (190, 190, 5, '실기');
--Python 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (191, 191, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (192, 192, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (193, 193, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (194, 194, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (195, 195, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (196, 196, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (197, 197, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (198, 198, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (199, 199, 6, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (200, 200, 6, '실기');
--Django 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (201, 201, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (202, 202, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (203, 203, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (204, 204, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (205, 205, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (206, 206, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (207, 207, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (208, 208, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (209, 209, 7, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (210, 210, 7, '실기');
--Flask 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (211, 211, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (212, 212, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (213, 213, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (214, 214, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (215, 215, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (216, 216, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (217, 217, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (218, 218, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (219, 219, 8, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (220, 220, 8, '실기');
--Swift 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (221, 221, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (222, 222, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (223, 223, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (224, 224, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (225, 225, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (226, 226, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (227, 227, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (228, 228, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (229, 229, 9, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (230, 230, 9, '실기');
--Kotlin 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (231, 231, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (232, 232, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (233, 233, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (234, 234, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (235, 235, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (236, 236, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (237, 237, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (238, 238, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (239, 239, 10, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (240, 240, 10, '실기');
--React 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (241, 241, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (242, 242, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (243, 243, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (244, 244, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (245, 245, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (246, 246, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (247, 247, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (248, 248, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (249, 249, 11, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (250, 250, 11, '실기');
--ElasticSearch 실기
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (251, 251, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (252, 252, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (253, 253, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (254, 254, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (255, 255, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (256, 256, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (257, 257, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (258, 258, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (259, 259, 12, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (260, 260, 12, '실기');
--데이터 구조 알고리즘
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (261, 261, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (262, 262, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (263, 263, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (264, 264, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (265, 265, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (266, 266, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (267, 267, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (268, 268, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (269, 269, 13, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (270, 270, 13, '실기');
--컴퓨터 이론
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (271, 271, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (272, 272, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (273, 273, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (274, 274, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (275, 275, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (276, 276, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (277, 277, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (278, 278, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (279, 279, 14, '실기');
INSERT INTO Tblexampaper(seq_attendancepapers, seq_question, seq_subject, kind) VALUES (280, 280, 14, '실기');


--교재 목록
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (1, 1, 1);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (2, 2, 1);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (3, 3, 6);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (4, 4, 3);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (5, 5, 9);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (6, 6, 10);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (7, 7, 11);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (8, 8, 2);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (9, 9, 5);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (10, 10, 5);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (11, 11, 7);
insert into tblTextbookList (seq_textbookList, seq_textbook, seq_subject) values (12, 12, 4);
insert into tblTextBookList values(13,13,8);
insert into tblTextBookList values(14,14,12);
insert into tblTextBookList values(15,15,13);
insert into tblTextBookList values(16,16,14);
insert into tblTextBookList values(17,17,15);
insert into tblTextBookList values(18,18,16);
insert into tblTextBookList values(19,19,17);

--교육 과정
insert into tblCurriculum values (1, 2,'AWS와 Docker를 활용한 Java Full-Stack 과정(A)', 
'Java 언어를 기반으로 AWS와 Docker를 활용하여 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (2, 2,'AWS 클라우드를 활용한 Full-Stack 과정(A)', 
'Java 언어를 기반으로 AWS 클라우드를 활용할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (3, 1,'AWS 클라우드와 Elasticsearch를 활용한 Java Full-Stack 과정(A)', 
'Java 언어를 기반으로 AWS 클라우드와 Elasticsearch를 활용할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (4, 2,'자바(Java)기반 Web과 스마트플랫폼 Full-Stack 과정(A)', 
'Java 언어를 기반으로 스마트웹,콘텐츠 개발을 할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (5, 2,'AWS와 Docker를 활용한 Java Full-Stack 과정(B)', 
'Java 언어를 기반으로 AWS와 Docker를 활용하여 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (6, 2,'AWS 클라우드를 활용한 Full-Stack 과정(B)', 
'Java 언어를 기반으로 AWS 클라우드를 활용할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (7, 1,'AWS 클라우드와 Elasticsearch를 활용한 Java Full-Stack 과정(B)', 
'Java 언어를 기반으로 AWS 클라우드와 Elasticsearch를 활용할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');
insert into tblCurriculum values (8, 2,'자바(Java)기반 Web과 스마트플랫폼 Full-Stack 과정(B)', 
'Java 언어를 기반으로 스마트웹,콘텐츠 개발을 할 수 있는 Full-Stack 개발자를 양성하고 있습니다.');


--면접 스케쥴
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(1, 2, 1, TO_DATE('2023-08-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(2, 3, 2, TO_DATE('2023-11-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(3, 4, 3, TO_DATE('2023-11-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(4, 5, 4, TO_DATE('2023-10-07', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(5, 6, 5, TO_DATE('2024-02-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(6, 7, 6, TO_DATE('2023-10-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(7, 8, 7, TO_DATE('2023-10-16', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(8, 9, 8, TO_DATE('2024-01-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(9, 10, 9, TO_DATE('2024-02-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(10, 1, 10, TO_DATE('2023-11-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(11, 2, 11, TO_DATE('2024-02-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(12, 3, 12, TO_DATE('2024-02-20', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(13, 4, 13, TO_DATE('2024-01-03', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(14, 5, 14, TO_DATE('2023-12-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(15, 6, 15, TO_DATE('2023-11-02', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(16, 7, 16, TO_DATE('2024-01-05', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(17, 8, 17, TO_DATE('2023-10-02', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(18, 9, 19, TO_DATE('2023-10-07', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(19, 10, 20, TO_DATE('2023-12-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(20, 1, 21, TO_DATE('2023-11-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(21, 2, 22, TO_DATE('2023-12-19', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(22, 3, 23, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(23, 4, 24, TO_DATE('2023-09-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(24, 5, 26, TO_DATE('2023-08-04', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(25, 6, 28, TO_DATE('2023-12-10', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(26, 7, 29, TO_DATE('2023-10-19', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(27, 8, 31, TO_DATE('2023-11-26', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(28, 9, 32, TO_DATE('2023-12-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(29, 10, 34, TO_DATE('2023-10-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(30, 1, 35, TO_DATE('2023-12-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(31, 2, 36, TO_DATE('2023-12-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(32, 3, 37, TO_DATE('2023-11-15', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(33, 4, 38, TO_DATE('2024-01-03', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(34, 5, 40, TO_DATE('2023-12-02', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(35, 6, 41, TO_DATE('2023-11-10', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(36, 7, 42, TO_DATE('2023-10-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(37, 8, 43, TO_DATE('2024-01-17', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(38, 9, 44, TO_DATE('2024-02-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(39, 10, 45, TO_DATE('2023-11-16', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(40, 1, 47, TO_DATE('2023-09-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(41, 2, 48, TO_DATE('2023-11-07', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(42, 3, 49, TO_DATE('2023-12-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(43, 4, 51, TO_DATE('2023-12-17', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(44, 5, 52, TO_DATE('2024-02-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(45, 6, 53, TO_DATE('2024-01-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(46, 7, 54, TO_DATE('2023-10-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(47, 8, 56, TO_DATE('2023-09-02', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(48, 9, 57, TO_DATE('2023-09-22', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(49, 10, 58, TO_DATE('2023-09-30', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(50, 1, 60, TO_DATE('2024-01-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(51, 2, 61, TO_DATE('2023-12-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(52, 3, 62, TO_DATE('2023-09-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(53, 4, 63, TO_DATE('2023-12-06', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(54, 5, 64, TO_DATE('2023-08-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(55, 6, 65, TO_DATE('2023-11-06', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(56, 7, 67, TO_DATE('2023-09-16', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(57, 8, 68, TO_DATE('2023-09-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(58, 9, 69, TO_DATE('2023-10-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(59, 10, 70, TO_DATE('2023-11-13', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(60, 1, 71, TO_DATE('2023-10-26', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(61, 2, 72, TO_DATE('2024-01-07', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(62, 3, 73, TO_DATE('2023-12-20', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(63, 4, 74, TO_DATE('2023-09-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(64, 5, 75, TO_DATE('2023-10-26', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(65, 6, 76, TO_DATE('2023-11-16', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(66, 7, 77, TO_DATE('2023-10-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(67, 8, 78, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(68, 9, 80, TO_DATE('2023-09-30', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(69, 10, 81, TO_DATE('2023-09-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(70, 1, 82, TO_DATE('2023-09-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(71, 2, 84, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(72, 3, 85, TO_DATE('2023-09-09', 'YYYY-MM-DD')); 
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(73, 4, 86, TO_DATE('2024-01-10', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(74, 5, 87, TO_DATE('2023-10-19', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(75, 6, 88, TO_DATE('2023-08-30', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(76, 7, 89, TO_DATE('2024-01-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(77, 8, 90, TO_DATE('2023-09-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(78, 9, 91, TO_DATE('2023-08-08', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(79, 10, 92, TO_DATE('2023-12-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(80, 1, 93, TO_DATE('2023-09-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(81, 2, 95, TO_DATE('2023-09-23', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(82, 3, 96, TO_DATE('2023-08-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(83, 4, 97, TO_DATE('2023-11-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(84, 5, 98, TO_DATE('2023-08-30', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(85, 6, 99, TO_DATE('2023-11-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(86, 7, 100, TO_DATE('2023-10-05', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(87, 8, 102, TO_DATE('2024-01-03', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(88, 9, 103, TO_DATE('2023-09-14', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(89, 10, 104, TO_DATE('2024-02-12', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(90, 1, 105, TO_DATE('2023-08-08', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(91, 2, 106, TO_DATE('2023-10-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(92, 3, 107, TO_DATE('2024-01-27', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(93, 4, 108, TO_DATE('2023-09-12', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(94, 5, 109, TO_DATE('2023-10-16', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(95, 6, 110, TO_DATE('2023-11-22', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(96, 7, 111, TO_DATE('2023-09-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(97, 8, 112, TO_DATE('2023-10-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(98, 9, 113, TO_DATE('2023-11-05', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(99, 10, 114, TO_DATE('2023-10-27', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(100, 1, 115, TO_DATE('2024-01-04', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(101, 10, 116, TO_DATE('2023-10-10', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(102, 2, 117, TO_DATE('2023-12-10', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(103, 7, 119, TO_DATE('2023-09-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(104, 4, 121, TO_DATE('2023-11-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(105, 3, 122, TO_DATE('2024-01-08', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(106, 9, 123, TO_DATE('2023-11-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(107, 7, 125, TO_DATE('2023-10-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(108, 10, 126, TO_DATE('2023-10-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(109, 2, 127, TO_DATE('2023-11-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(110, 10, 128, TO_DATE('2023-11-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(111, 4, 129, TO_DATE('2023-10-15', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(112, 6, 132, TO_DATE('2023-11-02', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(113, 6, 137, TO_DATE('2023-12-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(114, 5, 138, TO_DATE('2024-01-20', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(115, 3, 139, TO_DATE('2024-01-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(116, 7, 140, TO_DATE('2023-11-29', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(117, 6, 142, TO_DATE('2023-08-20', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(118, 1, 143, TO_DATE('2023-08-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(119, 3, 145, TO_DATE('2023-12-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(120, 8, 147, TO_DATE('2023-10-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(121, 2, 148, TO_DATE('2023-10-06', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(122, 9, 150, TO_DATE('2023-11-04', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(123, 10, 152, TO_DATE('2023-11-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(124, 5, 158, TO_DATE('2023-11-26', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(125, 10, 160, TO_DATE('2023-12-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(126, 6, 163, TO_DATE('2023-12-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(127, 3, 166, TO_DATE('2023-11-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(128, 4, 170, TO_DATE('2024-01-03', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(129, 7, 171, TO_DATE('2023-12-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(130, 7, 176, TO_DATE('2024-02-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(131, 2, 179, TO_DATE('2024-01-05', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(132, 9, 180, TO_DATE('2024-01-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(133, 9, 183, TO_DATE('2024-01-09', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(134, 1, 188, TO_DATE('2023-12-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(135, 6, 192, TO_DATE('2023-10-01', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(136, 9, 196, TO_DATE('2023-12-18', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(137, 10, 198, TO_DATE('2023-10-21', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(138, 5, 201, TO_DATE('2023-09-22', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(139, 3, 203, TO_DATE('2023-09-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(140, 6, 204, TO_DATE('2023-10-19', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(141, 10, 207, TO_DATE('2023-12-11', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(142, 4, 213, TO_DATE('2023-11-26', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(143, 8, 217, TO_DATE('2023-11-25', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(144, 10, 233, TO_DATE('2024-01-19', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(145, 4, 235, TO_DATE('2023-12-06', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(146, 5, 238, TO_DATE('2024-01-05', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(147, 5, 240, TO_DATE('2023-11-24', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(148, 1, 244, TO_DATE('2023-10-28', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(149, 8, 248, TO_DATE('2023-09-06', 'YYYY-MM-DD'));
insert into tblInterviewSchedule (seq_schedule, seq_manager, seq_trainee, day) values(150, 7, 250, TO_DATE('2023-11-03', 'YYYY-MM-DD'));


--강의 가능 과목 목록
insert into tblAvailableSubjectList values (1, 1, 1);
insert into tblAvailableSubjectList values (2, 2, 1);
insert into tblAvailableSubjectList values (3, 3, 1);
insert into tblAvailableSubjectList values (4, 4, 1);
insert into tblAvailableSubjectList values (5, 5, 1);
insert into tblAvailableSubjectList values (6, 6, 1);
insert into tblAvailableSubjectList values (7, 7, 1);
insert into tblAvailableSubjectList values (8, 8, 1);
insert into tblAvailableSubjectList values (9, 9, 1);
insert into tblAvailableSubjectList values (10, 10, 1);
insert into tblAvailableSubjectList values (11, 11, 1);
insert into tblAvailableSubjectList values (12, 12, 1);
insert into tblAvailableSubjectList values (13, 13, 1);
insert into tblAvailableSubjectList values (14, 14, 1);
insert into tblAvailableSubjectList values (15, 1, 2);
insert into tblAvailableSubjectList values (16, 2, 2);
insert into tblAvailableSubjectList values (17, 3, 2);
insert into tblAvailableSubjectList values (18, 4, 2);
insert into tblAvailableSubjectList values (19, 5, 2);
insert into tblAvailableSubjectList values (20, 6, 2);
insert into tblAvailableSubjectList values (21, 7, 2);
insert into tblAvailableSubjectList values (22, 8, 2);
insert into tblAvailableSubjectList values (23, 9, 2);
insert into tblAvailableSubjectList values (24, 10, 2);
insert into tblAvailableSubjectList values (25, 11, 2);
insert into tblAvailableSubjectList values (26, 12, 2);
insert into tblAvailableSubjectList values (27, 13, 2);
insert into tblAvailableSubjectList values (28, 14, 2);
insert into tblAvailableSubjectList values (29, 1, 3);
insert into tblAvailableSubjectList values (30, 2, 3);
insert into tblAvailableSubjectList values (31, 3, 3);
insert into tblAvailableSubjectList values (32, 4, 3);
insert into tblAvailableSubjectList values (33, 5, 3);
insert into tblAvailableSubjectList values (34, 6, 3);
insert into tblAvailableSubjectList values (35, 7, 3);
insert into tblAvailableSubjectList values (36, 8, 3);
insert into tblAvailableSubjectList values (37, 9, 3);
insert into tblAvailableSubjectList values (38, 10, 3);
insert into tblAvailableSubjectList values (39, 12, 3);
insert into tblAvailableSubjectList values (40, 13, 3);
insert into tblAvailableSubjectList values (41, 14, 3);
insert into tblAvailableSubjectList values (42, 1, 4);
insert into tblAvailableSubjectList values (43, 2, 4);
insert into tblAvailableSubjectList values (44, 3, 4);
insert into tblAvailableSubjectList values (45, 4, 4);
insert into tblAvailableSubjectList values (46, 5, 4);
insert into tblAvailableSubjectList values (47, 6, 4);
insert into tblAvailableSubjectList values (48, 7, 4);
insert into tblAvailableSubjectList values (49, 8, 4);
insert into tblAvailableSubjectList values (50, 9, 4);
insert into tblAvailableSubjectList values (51, 11, 4);
insert into tblAvailableSubjectList values (52, 12, 4);
insert into tblAvailableSubjectList values (53, 13, 4);
insert into tblAvailableSubjectList values (54, 14, 4);
insert into tblAvailableSubjectList values (55, 1, 5);
insert into tblAvailableSubjectList values (56, 2, 5);
insert into tblAvailableSubjectList values (57, 3, 5);
insert into tblAvailableSubjectList values (58, 4, 5);
insert into tblAvailableSubjectList values (59, 5, 5);
insert into tblAvailableSubjectList values (60, 6, 5);
insert into tblAvailableSubjectList values (61, 7, 5);
insert into tblAvailableSubjectList values (62, 12, 5);
insert into tblAvailableSubjectList values (63, 13, 5);
insert into tblAvailableSubjectList values (64, 14, 5);
insert into tblAvailableSubjectList values (65, 1, 6);
insert into tblAvailableSubjectList values (66, 2, 6);
insert into tblAvailableSubjectList values (67, 3, 6);
insert into tblAvailableSubjectList values (68, 4, 6);
insert into tblAvailableSubjectList values (69, 5, 6);
insert into tblAvailableSubjectList values (70, 6, 6);
insert into tblAvailableSubjectList values (71, 7, 6);
insert into tblAvailableSubjectList values (72, 8, 6);
insert into tblAvailableSubjectList values (73, 9, 6);
insert into tblAvailableSubjectList values (74, 11, 6);
insert into tblAvailableSubjectList values (75, 12, 6);
insert into tblAvailableSubjectList values (76, 13, 6);
insert into tblAvailableSubjectList values (77, 14, 6);
insert into tblAvailableSubjectList values (78, 1, 7);
insert into tblAvailableSubjectList values (79, 2, 7);
insert into tblAvailableSubjectList values (80, 3, 7);
insert into tblAvailableSubjectList values (81, 4, 7);
insert into tblAvailableSubjectList values (82, 5, 7);
insert into tblAvailableSubjectList values (83, 6, 7);
insert into tblAvailableSubjectList values (84, 7, 7);
insert into tblAvailableSubjectList values (85, 9, 7);
insert into tblAvailableSubjectList values (86, 11, 7);
insert into tblAvailableSubjectList values (87, 12, 7);
insert into tblAvailableSubjectList values (88, 1, 8);
insert into tblAvailableSubjectList values (89, 2, 8);
insert into tblAvailableSubjectList values (90, 3, 8);
insert into tblAvailableSubjectList values (91, 4, 8);
insert into tblAvailableSubjectList values (92, 5, 8);
insert into tblAvailableSubjectList values (93, 6, 8);
insert into tblAvailableSubjectList values (94, 7, 8);
insert into tblAvailableSubjectList values (95, 9, 8);
insert into tblAvailableSubjectList values (96, 11, 8);
insert into tblAvailableSubjectList values (97, 12, 8);
insert into tblAvailableSubjectList values (98, 1, 9);
insert into tblAvailableSubjectList values (99, 2, 9);
insert into tblAvailableSubjectList values (100, 3, 9);
insert into tblAvailableSubjectList values (101, 4, 9);
insert into tblAvailableSubjectList values (102, 5, 9);
insert into tblAvailableSubjectList values (103, 6, 9);
insert into tblAvailableSubjectList values (104, 7, 9);
insert into tblAvailableSubjectList values (105, 8, 9);
insert into tblAvailableSubjectList values (106, 11, 9);
insert into tblAvailableSubjectList values (107, 12, 9);
insert into tblAvailableSubjectList values (108, 1, 10);
insert into tblAvailableSubjectList values (109, 2, 10);
insert into tblAvailableSubjectList values (110, 3, 10);
insert into tblAvailableSubjectList values (111, 4, 10);
insert into tblAvailableSubjectList values (112, 5, 10);
insert into tblAvailableSubjectList values (113, 6, 10);
insert into tblAvailableSubjectList values (114, 7, 10);
insert into tblAvailableSubjectList values (115, 8, 10);
insert into tblAvailableSubjectList values (116, 9, 10);
insert into tblAvailableSubjectList values (117, 10, 10);
insert into tblAvailableSubjectList values (118, 11, 10);
insert into tblAvailableSubjectList values (119, 12, 10);
insert into tblAvailableSubjectList values (120, 15, 1);
insert into tblAvailableSubjectList values (121, 15, 2);
insert into tblAvailableSubjectList values (122, 15, 3);
insert into tblAvailableSubjectList values (123, 15, 4);
insert into tblAvailableSubjectList values (124, 15, 5);
insert into tblAvailableSubjectList values (125, 15, 6);
insert into tblAvailableSubjectList values (126, 15, 7);
insert into tblAvailableSubjectList values (127, 15, 8);
insert into tblAvailableSubjectList values (128, 15, 9);
insert into tblAvailableSubjectList values (129, 15, 10);
insert into tblAvailableSubjectList values (130, 16, 1);
insert into tblAvailableSubjectList values (131, 16, 2);
insert into tblAvailableSubjectList values (132, 16, 3);
insert into tblAvailableSubjectList values (133, 16, 4);
insert into tblAvailableSubjectList values (134, 16, 5);
insert into tblAvailableSubjectList values (135, 16, 6);
insert into tblAvailableSubjectList values (136, 16, 7);
insert into tblAvailableSubjectList values (137, 16, 8);
insert into tblAvailableSubjectList values (138, 16, 9);
insert into tblAvailableSubjectList values (139, 16, 10);
insert into tblAvailableSubjectList values (140, 17, 1);
insert into tblAvailableSubjectList values (141, 17, 2);
insert into tblAvailableSubjectList values (142, 17, 3);
insert into tblAvailableSubjectList values (143, 17, 4);
insert into tblAvailableSubjectList values (144, 17, 5);
insert into tblAvailableSubjectList values (145, 17, 6);
insert into tblAvailableSubjectList values (146, 17, 7);
insert into tblAvailableSubjectList values (147, 17, 8);
insert into tblAvailableSubjectList values (148, 17, 9);
insert into tblAvailableSubjectList values (149, 17, 10);


--추천 교재 목록
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (1, 1, 1, 4);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (2, 1, 2, 4);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (3, 1, 3, 3);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (4, 2, 4, 5);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (5, 2, 5, 5);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (6, 3, 6, 3);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (7, 4, 7, 5);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (8, 5, 8, 5);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (9, 6, 9, 4);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (10, 7, 10, 2);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (11, 8, 11, 2);
insert into tblRecommendTextbook (seq_recommendTextbook, seq_teacher, seq_textbook, grade) values (12, 9, 12, 2);

commit;